### ISSUE TITLE
Schematics: Add checks/warnings for unconnected wires

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#1054]
##### SUMMARY

On a recent project, I debugged a non-working board on the workbench for half an hour... Until I found this:

![image](https://user-images.githubusercontent.com/105168/194638801-4b7f5aed-b904-4e19-93b8-ec1e825e7d93.png)

The connection wasn't done properly, yet no ERC warning was emitted.

##### SOLUTION

- If a wire is not connected on both sides, show a warning in the ERC about an unconnected wire
- To silence this warning, either connect the wire or explicitly mark it as unconnected
- To handle the case where the wire is only used to place a netlabel: Warn if a netlabel is attached that only exists once in the schematic. Do not warn if a netlabel is attached that is also present on other wires.

Prior art: In KiCAD, connections must be marked as unconnected as well.

![screenshot-20221007-212941](https://user-images.githubusercontent.com/105168/194639581-e2dd4555-351c-4251-8217-a77a9364ed19.png)

The tool to do so can be found in the toolbar, next to the tools used to draw wires, add labels, etc.

![screenshot-20221007-213230](https://user-images.githubusercontent.com/105168/194639956-16c6594c-d6ce-41c0-b61f-14af930d600c.png)

To me, this solution feels quite natural. We could even add a way to add these no-connection flags through the ERC (right-click warning, choose "Add no-connection flag").

**Comment by ubruhin** [comment]
I agree that in your example there should appear an ERC error. Just some comments:

> If a wire is not connected on both sides, show a warning in the ERC about an unconnected wire

Sounds reasonable, I don't see a case where such a warning would be annoying :+1:

> Warn if a netlabel is attached that only exists once in the schematic.

Indirectly this is already the case. If there's a net (no matter of how many split segments it consists of) which is connected to less than two symbol pins, an ERC warning is raised. This covers even more error cases.

> Prior art: In KiCAD, connections must be marked as unconnected as well.

This is one of the (many) reasons why I don't like KiCad ;) IMHO it's stupid if the schematic editor assumes that EVERY pin needs to be connected, since in real world that's (by far) not the case. Therefore in LibrePCB the information of whether a pin is required or optional is specified in the component library element, and the ERC warns only about unconnected *required* pins since this is not annoying but still very helpful. However, it might make sense to optionally allow configuring the ERC to be more restrictive :thinking: 

But, since all these variants still don't cover your specific problem: I see two options for that one:

- Either warn if a line ends on another line without having a connection, i.e. detect the *visual* issue instead of a *logic* issue. This would cover the most tricky cases, but it would still not warn if there's no overlap (e.g. if the line in your example was 1 grid interval shorter).
- Or, warn about lines with open ends which do not have a netlabel assigned, since open ends make sense only for netlabels. However, LibrePCB doesn't know to which line a netlabel belongs to (a netlabel is a floating object), this is a bit inaccurate as well - there could be a netlabel far away from the open end which unintentionally suppresses the ERC warning.

Both variants would cover your specific case. But the first one is much more complicated to implement :see_no_evil:

**Comment by dbrgn** [comment]
> This is one of the (many) reasons why I don't like KiCad ;) IMHO it's stupid if the schematic editor assumes that EVERY pin needs to be connected, since in real world that's (by far) not the case.

That's not what I was suggesting, only if a wire is attached to the pin 🙂

This is fine (no wires attached):

![screenshot-20221008-214514](https://user-images.githubusercontent.com/105168/194725341-6cb8a75f-bce9-40a5-8526-634340532044.png)

This is not OK (wire attached, no netlabel):

![screenshot-20221008-214553](https://user-images.githubusercontent.com/105168/194725390-13cd09a8-2f66-4152-a4bd-492a72f9708b.png)

This is not OK (wire attached, with netlabel, but netlabel is not attached to any other net). I think this already results in a warning.

![screenshot-20221008-214602](https://user-images.githubusercontent.com/105168/194725460-b43bc5ee-8910-437e-afc5-59524102fbfc.png)

This is OK, wire is attached through netlabel.

![screenshot-20221008-214642](https://user-images.githubusercontent.com/105168/194725471-f6f77c2f-09fa-49a5-9edc-983909997f9c.png)

**Comment by Tubbles** [comment]
Related #823
