### ISSUE TITLE
Provide Imperial paper size options

### ISSUE THREAD

**Issue by hooperbloob** [LibrePCB/LibrePCB#1075]
##### SUMMARY
The schematic editor currently provides for all the common metric/European page sizes 
but it would be great to include North American legal, letter, and ledger page sizes as well.

##### SOLUTION
Include the following page sizes:

Letter  8.5 x 11"
Legal   8.5 x 14"
Ledger 11 x 17"

**Comment by ubruhin** [comment]
Since this request is related only to the base library (schematic frames are not a built-in feature), I opened https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/issues/98 and will close this issue.

In the mean time, you have two options:
- Use similar-sized metric schematic frames. It does not define the paper size when printing, so you can just print e.g. an A4 schematic onto a Letter paper.
- Create your own schematic frame symbols + component for imperial sizes in your local library. It's done in a few minutes when using the "Duplicate Library Element" feature in the library editor.
