### ISSUE TITLE
How to go about proposing/contributing new libraries to Librepcb-libraries?

### ISSUE THREAD

**Issue by kotchin** [LibrePCB/LibrePCB#1173]
I would like to help build new libraries for LibrePCB. 

Currently, I don't know if opening a new issue in [LibrePCB-libraries](https://github.com/LibrePCB-Libraries) is a good idea as I don't know which library to open the issue in as it will be irrelevant to that library hence why I'm posting here.

I'm wondering if you'd be willing to expand the current list of libraries and if you are, what is the recommended flow for us contributors? I would like to propose things such as USB traces and other popular connectors, in addition to some specific ones for [Framework](https://frame.work) (I'm not affiliated) where (among others) they have an open connector for [expansion bay](https://github.com/FrameworkComputer/ExpansionBay) they are currently working on. Let me know if you'd be interested.

Edit: I see USB traces are already in the unofficial LibrePCB libraries, but I hope my point is still understood. I would also like to add that I already have a symbol, package and device for the framework expansion bay that I'd like to share, which is the purpose of my initial request.
Edit2: corrected the company website.

**Comment by ubruhin** [comment]
Hi,

> Currently, I don't know if opening a new issue in [LibrePCB-libraries](https://github.com/LibrePCB-Libraries) is a good idea as I don't know which library to open the issue in as it will be irrelevant to that library hence why I'm posting here.

For library related topics, generally the [forum](https://librepcb.discourse.group/) is the preferred place to discuss.

> I'm wondering if you'd be willing to expand the current list of libraries and if you are, what is the recommended flow for us contributors?

Of course we can add more libraries and then contributors can open pull requests to add elements to it. But to get them merged, it is crucial to precisely follow our (incomplete) [library conventions](https://librepcb.org/docs/library-conventions/) and have a consistent look&feel as our other libraries. At the moment we are unfortunately not able to spend lots of time for library review & discussion because of limited resources. See also the corresponding note [on our website](https://librepcb.org/contribute/).

If you are OK with this, you're welcome to create pull requests. I could create a library for the Framework parts if needed - did I understand correctly that the manufacturer of these connectors is the Framework project? Or is it some standard connector? Where can it be purchased?

**Comment by kotchin** [comment]
Thank you, I was unaware of the forum.

I understand your concern regarding the workload of verifying following the library conventions. This is an important point indeed.

Regarding questions for the connector, it's a two part answer:
1) the footprint is the same as for the DGFF connector by Dell. A compatible connector can be purchased [here](https://www.cdrtd.com/products/laptop-dgff-board-to-board-graphic-connector-for-dell-precision-7530-7540-7550-7560-7730-7740-7750-7760-ufk1836-0ngrjg-ngrjg-new.html) (as an example, not affialated in anway)
2) The pinout is an specific to Framework as Dell did not release specifications for their pinout. The pinout details are provided in Framework's github repository, which I linked to above. 

The footprint and symbol are both rather extensive, involving a significant number of pins and 148 pads respectively. I have already created them both and am currently in the process of accomodating them both to the conventions you described.

**Comment by ubruhin** [comment]
OK thanks for the information. I have now created a library for the Framework footprints etc: https://github.com/LibrePCB-Libraries/Framework_Computer.lplib

It is not published via the library manager as long as it is empty, but it is now ready to receive pull requests. I'd be happy to see contributions, but please don't be afraid if review takes a long time. The higher quality the contributions are, the more likely it will be reviewed in depth and finally merged :slightly_smiling_face: 

I'll close this issue since the initial question should be clear now (it's sill possible to comment).
