### ISSUE TITLE
Support importing Eagle projects

### ISSUE THREAD

**Issue by shufps** [LibrePCB/LibrePCB#1268]
What I wondered ... It already looks like Eagle - perhaps it would be nice if it could become Eagle-compatible or even a clone.

Would give you a big user base with all Eagle users that are unsatisfied with what Eagle became (or is becoming like EOL after completly consumed by Autodesk)

**Comment by ubruhin** [comment]
An Eagle clone makes no sense because of the different concepts and file format. In the end we want to do it better, not just the same way as Eagle. But an Eagle project file importer would be nice so a transition path from Eagle to LibrePCB exists (just as already existing for the Eagle libraries). I changed the issue title accordingly.
