### ISSUE TITLE
Relay coil symbol for IEEE 315 shows a box instead of a coil.

### ISSUE THREAD

**Issue by hooperbloob** [LibrePCB/LibrePCB#1285]
The relay symbol for the IEEE-315 variation should be rendered as a looping wire (like the IEEE-315 inductor) instead of the box currently shown.

**Comment by ubruhin** [comment]
Hm I'm not sure if there is really an IEEE 315 relay symbol, I didn't find any references about that. Also I need to close this issue anyway because it's not related to this repository.

If you are sure there's an IEEE 315 relay symbol, please open a new issue at [LibrePCB_Base.lplib](https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib) and provide some references which show how the symbol should look like. Thanks.
