### ISSUE TITLE
Wrong colors for identical objects in STEP files

### ISSUE THREAD

**Issue by ekawahyu** [LibrePCB/LibrePCB#1286]
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version:
Release: 1.0.0
Operating System: macOS Monterey
```

##### SUMMARY
I created a simple SMD capacitor-like object, with 3 different colors on it, red-yellow-blue. It seems that only two colors appear in the library editor. I verified that the STEP file has 3 different colors with FreeCAD. See the following figure:

![Screen Shot 2024-01-14 at 3 48 31 PM](https://github.com/LibrePCB/LibrePCB/assets/764438/83645a9c-5fe3-4c8c-8713-8d5861f85953)

Apparently, this happens when there are two or more identical objects in the file, like those two capacitor leads that I made identical on purpose. However, when one of the lead size is slightly smaller or larger by any number, then all three colors show up just fine. See below:

![Screen Shot 2024-01-14 at 3 51 25 PM](https://github.com/LibrePCB/LibrePCB/assets/764438/c6f3f1f8-2af6-4598-a3bf-1e097682efad)

##### STEPS TO REPRODUCE
Create new component in library editor and add STEP file that contains at least two identical objects in it but with different color. The second object will have the same color as the first one.

##### EXPECTED RESULTS
Identical object with different color should show up with its own color.

##### ADDITIONAL INFO
It seems that no matter how many objects I add with different colors, if they all are identical, only one color is applied to all of them.

![Screen Shot 2024-01-14 at 11 08 10 PM](https://github.com/LibrePCB/LibrePCB/assets/764438/9a113b2e-b7bc-407c-a4d1-a473a3af053c)

**Comment by ubruhin** [comment]
Hi, could you upload your STEP file here to allow us reproducing the issue with the same model?

**Comment by ekawahyu** [comment]
Zip file containing the FreeCAD source file and the the generated STEP:

[Capacitor Test.zip](https://github.com/LibrePCB/LibrePCB/files/13944054/Capacitor.Test.zip)

**Comment by ubruhin** [comment]
I started to investigate this issue, and it turned out the problem must be located in `OccModel::minifyStep()` because without the minification your STEP model is rendered correctly. I didn't investigate it further yet so I don't know the exact problem, but at least it's good to know the root cause must be located in our own code.

Actually this would be a good issue for contributors since it doesn't require further knowledge about our code base, so any help on this issue would be very welcome!

Btw, in the mean time there's a workaround available:

1. Load the STEP model into the package editor - it will be rendered wrong.
2. Click *File -> Show in File Manager* to open the package in the file manager.
3. There will be a *.step file in the directory (with a UUID as filename). Replace this file with your original filename, but keep the UUID filename (i.e. replace only its contents).
4. Close and re-open the package in the library manager. The STEP model should now be rendered correctly.

**Comment by Xenia1423** [comment]
Hello, @ekawahyu ! Can you give me your email address? Or you can contact me at: brilliantstone@yahoo.com. I have some questions about some of your projects. Thank you!
