### ISSUE TITLE
Compilation is broken due to this error: no member named 'construct' in 'optional<type-parameter-0-0 &>'

### ISSUE THREAD

**Issue by yurivict** [LibrePCB/LibrePCB#1454]
```
In file included from /wrkdirs/usr/ports/cad/librepcb/work/librepcb-1.1.0/libs/librepcb/core/3d/../geometry/../serialization/../types/uuid.h:30:
/wrkdirs/usr/ports/cad/librepcb/work/librepcb-1.1.0/libs/optional/tl/optional.hpp:1989:11: error: no member named 'construct' in 'optional<type-parameter-0-0 &>'
 1989 |     this->construct(std::forward<Args>(args)...);
      |     ~~~~  ^
1 error generated.
```

The error appeared after llvm/clang was updated in the FreeBSD base.

There is really no method 'load' in the class in question, so it's amazing that this class is even compiled by any C++ compiler.

[log](https://pkg-status.freebsd.org/beefy18/data/main-amd64-default/p332c73b035e3_sf377a0c7dfa/logs/librepcb-1.1.0_1.log)

##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 1.1.0
Operating System: FreeBSD 14.1
```

**Comment by ubruhin** [comment]
Very strange - never saw this issue and we're compiling LibrePCB with several different compilers on CI (including Clang).

Some ideas:

- You could try to replace the `optional.hpp` file with the latest upstream version from [here](https://github.com/TartanLlama/optional/blob/master/include/tl/optional.hpp). I quickly checked the diff and didn't see a relevant change, but still worth a try.
- Maybe the problem is related to these warning at the top of your log?
  ```
  !!! Jail is newer than host. (Jail: 1500026, Host: 1500023) !!!
  !!! This is not supported. !!!
  !!! Host kernel must be same or newer than jail. !!!
  !!! Expect build failures. !!!  
  ```
- Clang 19.1.2 is bleeding edge (released 2 weeks ago), could you use an older version instead?
- Use GCC instead?

Note that the next LibrePCB release will probably be the last one using the `tl::optional` library, I think afterwards we have to switch entirely to C++17 and thus can use `std::optional`, hopefully fixing the problem too.

**Comment by yurivict** [comment]
The function "construct" is missing in this class so this is a legitimate C++ error.
All previous compilers were wrong when they didn't complain about this.

Could you please consider to make a bugfix release fixing this issue?

**Comment by ubruhin** [comment]
Yes there is a construct method:

https://github.com/LibrePCB/optional/blob/89d6d30587fcb8c3bb7297370f0f91e85f437982/tl/optional.hpp#L409-L412

This file has not been modified since 5 years and compiled with many different compilers fine. I doubt it's an error in the file, at least not a critical one. And it will be removed soon anyway, so it makes more sense to find another (possibly temporary) solution.

But if the latest upstream version fixes the problem, I'm willing to update it.

**Comment by yurivict** [comment]
> Yes there is a construct method (though the template magic is hard to understand...):

The "construct" method is defined in a different class.

**Comment by yurivict** [comment]
> I can't believe it's an error in the file, at least not a critical one.

It's critical enough to break the compilation. I am sure you'll see more people complaining about this when the latest clang would be used more.

**Comment by ubruhin** [comment]
> The "construct" method is defined in a different class.

It's in a base class. The "class" where the error occurs is a template specialization, not a class definition. Throuth several inheritance levels the construct method is inherited down to this specialization.

> I am sure you'll see more people complaining about this when the latest clang would be used more.

But we still don't know if the problem is in the file or in Clang. Maybe the bleeding edge Clang has a bug? And as I said, the file will be removed soon so it makes more sense to find a workaround for your case instead of spending many hours investigating the problem. Time solves the problem automatically.

**Comment by ubruhin** [comment]
Also I cannot fix a problem which I can't reproduce. I need your help since only you see the problem. So could you please check if the latest `optional.hpp` solves the problem? That would be an easy fix then.

**Comment by yurivict** [comment]
> It's in a base class.

The base classes are private here:
```
template <class T>
class optional : private detail::optional_move_assign_base<T>,
                 private detail::optional_delete_ctor_base<T>,
                 private detail::optional_delete_assign_base<T> {
```
therefore methods defined w/in then aren't visible.
This is why the error is legit.

I can't easily verify the fix since I don't have an easy access to such FreeBSD 15 systems.

**Comment by ubruhin** [comment]
I'm trying to understand the problem. I think I can confirm there's a bug in this header. However, we never call the mentioned `emplace()` method and since it's a template function, the compiler should not instantiate it (so it should compile even if there's invalid code). I suspect this is the reason why it always compiled fine the past years.

I don't know why Clang 19.1.2 instantiates the `emplace()` method. But I just figured out that Alpine Edge provides this Clang version and I'm now trying to reproduce it there.

Probably the easiest workaround is to just delete the `emplace()` function as we don't need it.

Anyway, I can't make a bugfix release for LibrePCB 1.1.0. The next release is planned in 4-8 weeks anyway. If you want it earlier, just apply a patch before compilation (this is usual practice for deployment issues and should be easy with any deployment system).

**Comment by ubruhin** [comment]
OK regardless of whether Clang is right or not, I can reproduce it on Alpine Edge. And as suggested, deleting the emplace function fixes the problem.

Within the `libs/optional/` directory, create a file `fix-optional.patch` with this content:

```patch
diff --git a/tl/optional.hpp b/tl/optional.hpp
index 531e8a7..74cc6cb 100644
--- a/tl/optional.hpp
+++ b/tl/optional.hpp
@@ -1979,17 +1979,6 @@ public:
     return *this;
   }
 
-  /// Constructs the value in-place, destroying the current one if there is
-  /// one.
-  template <class... Args> T &emplace(Args &&... args) noexcept {
-    static_assert(std::is_constructible<T, Args &&...>::value,
-                  "T must be constructible with Args");
-
-    *this = nullopt;
-    this->construct(std::forward<Args>(args)...);
-    return value();
-  }
-
   void swap(optional &rhs) noexcept { std::swap(m_value, rhs.m_value); }
 
   /// Returns a pointer to the stored value
```

Then apply it with git:

```
cd libs/optional
git apply fix-optional.patch
```

Afterwards it compiles successfully. I'll include this fix in the next release but it would be nice if you package LibrePCB 1.1.0 with this patch so we can see if any other problem occurs on FreeBSD.

**Comment by ubruhin** [comment]
See #1456

Instead of applying the patch manually, you could now just overwrite the file with downloading the new version:

```
wget -O libs/optional/tl/optional.hpp "https://github.com/LibrePCB/optional/raw/893af96be3d13b757c03d352c6ccc0d0cde7c50d/tl/optional.hpp"
```

**Comment by yurivict** [comment]
Ok, thanks.
I've added this patch.
