### ISSUE TITLE
how to add component and there's no help doc or wiki for instructions

### ISSUE THREAD

**Issue by 243750496** [LibrePCB/LibrePCB#197]
![add component](https://user-images.githubusercontent.com/6311930/33229236-362bf30c-d206-11e7-89af-22a41380cc71.png)

1.how to add component
i have done installed all library 
![all installed](https://user-images.githubusercontent.com/6311930/33229260-90434890-d206-11e7-8dc5-b42836029c59.png)

2.there's no help doc or wiki for instructions
where can i get the help doc or articles about how to use librepcb ?

3.how to convert kicad library to librepcb?
https://github.com/tmk/kicad_lib_tmk
i need this library for me to working on creating my own keyboard .

thx a lot

**Comment by ubruhin** [comment]
Hi,

These libraries are currently all empty because the file format is not yet considered as stable. You can get working libraries by using the [demo workspace](https://github.com/LibrePCB/demo-workspace). See [the Workspace section in the bottom of README.md](https://github.com/LibrePCB/LibrePCB#workspace):

> Note: As LibrePCB is still under heavy developement, it's highly recommended to use this demo workspace. Otherwise you won't be able to create/use any components and some parts of the application will not work properly.

I will think about how to improve this, because it's kind of annoying for new users.

> 2.there's no help doc or wiki for instructions

That's true, currently the only "getting started instructions" are in the README.md, but these needs to be improved a lot.

> 3.how to convert kicad library to librepcb?

Thats not (yet) possible. Converting Eagle libraries is kind of possible, but the converter is not yet integrated into LibrePCB. But please note that LibrePCB uses a library concept which is quite different from KiCad and Eagle, and thus converted libraries will never be as powerful as native LibrePCB libraries.

**Comment by 243750496** [comment]
i create my own libraries but can not find anywhere to add components from my lib (not empty)
and 
then i tried to copy it to new working space and load it , but still can't add any components of mine (create by myself , not copy and not reedit ),
at last i try to recreate all and delete demo working space but with try several times of restart still get a empty list 

could you please help me?

**Comment by ubruhin** [comment]
Replaced by #199 and #205.
