### ISSUE TITLE
Add Status section to README

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#222]
It would be good to add a section to the README that describes what the current status is. Stuff like:

- What features are already working?
- What's missing?
- What are the limitations? What are known bugs?
- What are the big milestones for the first release?

**Comment by ubruhin** [comment]
I added such a section to the documentation because this information is not only relevant for developers, but also for (potential) users: https://github.com/LibrePCB/librepcb-doc/pull/1

In the readme of this repository I will probably just add a link to the new project status section of the documentation.
