### ISSUE TITLE
Add arc drawing tool

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#354]
##### SUMMARY

Add a tool for drawing arcs in schematics, library elements and on the PCB.

##### SOLUTION

I could imagine a tool that would default to to a 45° arc by default. It could be either clockwise or counterclockwise. Right clicking would change the orientation, the scrollwheel would change the angle.

Additionally, entering exact values should be possible too, while drawing.

**Comment by brim2full** [comment]
:+1: 

brim2full

**Comment by ubruhin** [comment]
> I could imagine a tool that would default to to a 45° arc by default. It could be either clockwise or counterclockwise. Right clicking would change the orientation, the scrollwheel would change the angle.

After thinking a bit about this, it's not that easy :wink: Mechanical CADs provide several different ways to create an arc (3 points on arc, center + 2 points, center + radius + angle, ...). However, I think it would be overkill to implement all these ways in an EDA tool. So I hacked around until I found a solution which is quite easy to use and should be fine for most use-cases:

![librepcb-arc](https://user-images.githubusercontent.com/5374821/107892037-bf0fff80-6f22-11eb-8993-bc204daaf028.gif)

1. The first click specifies the center of the arc. 
2. The second click freezes the start point of the arc (and thus also its radius).
3. The third click freezes the end point of the arc, while keeping the radius specified with the previous click.

Memorizing the last cursor position into account to determine in which direction the arc should be drawn feels very intuitive in my opinion, and eliminates the need for a toolbar widget to *configure* the arc direction.

Any thoughts about this solution?

> Additionally, entering exact values should be possible too, while drawing.

:+1: Not implemented yet, but I think with the idea above it should be possible to add toolbar widgets where the user can optionally specify the radius and the angle instead of choosing them with the cursor.

**Comment by dbrgn** [comment]
Oh, this looks really cool for some use cases!

It would be good if the construction lines would have a different look than the actual arc though. And there should be some kind of guide in the UI how the tool is used, maybe a title text on the toolbar item?

One other issue is that some use cases, e.g. drawing rounded corners in an otherwise rectangular polygon, become tricky to draw graphically. In those cases, you usually want to draw the start point and the end point, and then adjust the angle. Depending on the desired radius, it can be very hard to find out where to click first.

Maybe we really need to different drawing modes for arcs?

**Comment by brim2full** [comment]
I agree, this would be a useful addition.  I can see it being particularly useful for board outlines, cut-outs and perhaps outlines for odd shape devices.  However the 'Line tool' offers all the functionality and convenience required for drawing an arc its just not obvious that it does.  I'm think the general solution may be simpler. 

When a line is drawn between two points one has effectively defined the start and end points of an arc but the angle value defaults to 0deg.  Perhaps the solution is to simply renaming the 'Angle' heading to 'Arc Angle' to signify its associated with an arc.  Thus an arc tool would pop-up a very similar properties window, to that of the line tool, but with clearer headings and a non zero angle value, may be even a clearer layout.

This may seem going off topic but since I inadvertently raised layout.  Is there an opportunity to change the properties dialogue box such that, when a line is drawn is drawn between two points, the angle parameter is not shown (its superfluous in a line context).  Also a line start and end points would be displayed in separate x, y columns but on the same line.  The next line is then on the next line of the property dialogue (to many lines in this sentence).

The arc properties dialogue would have the same basic layout as for the line tool but includes a non zero arc angle parameter.

I see the main advantages as:

    being a simple implementation (most of the code is likely to already exist),
    it clarifies the the properties dialogue for each use case,
    comparable with existing operation and editing of any polygon.

I think there is also an opportunity (later) to provide alternative dialogues and the capability to switch between them.  Thereby allowing the most appropriate dialogue to be chosen for the editing task.

**Comment by ubruhin** [comment]
> It would be good if the construction lines would have a different look than the actual arc though. And there should be some kind of guide in the UI how the tool is used, maybe a title text on the toolbar item?

:+1: will try to implement something like that...

> One other issue is that some use cases, e.g. drawing rounded corners in an otherwise rectangular polygon, become tricky to draw graphically. In those cases, you usually want to draw the start point and the end point, and then adjust the angle. Depending on the desired radius, it can be very hard to find out where to click first.

Well, the arc tool is not usable for this case anyway. The arc tool creates only a single arc, but for a rectangular polygon with rounded corners you don't want to draw 4 separate lines and 4 separate arcs, but just a single polygon. This could be implemented for example by a context menu item to round existing polygon corners, no need for a separate tool for this.

@brim2full yeah actually the "draw line", "draw polygon", "draw rect" and this new "draw arc" tools are in fact a single tool in the source code - it's a generic "draw polygon" tool which has slightly different behavior depending on which toolbar button was clicked to start this tool. Actually I'm not fully happy with that, especially the "draw line" and the "draw polygon" tools are *very* similar. I'll think about this, maybe I can find a solution with less tools to make it less confusing for the user...

**Comment by dbrgn** [comment]
> This could be implemented for example by a context menu item to round existing polygon corners, no need for a separate tool for this.

True. That would actually be pretty cool, and shouldn't be that hard to implement!

I think I'll create an issue with a proposal, and mark it as "good first issue".
