### ISSUE TITLE
Library Editor: "Save Element" and "Remove Element" should be visible only while element is in editing mode

### ISSUE THREAD

**Issue by Symbian9** [LibrePCB/LibrePCB#384]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.0
Git Revision:     d7458d3b3e126499902e1a66a0ef889f516a7c97
Build Date:       2018-11-24T16:25:35
Qt Version:       5.9.1 (built against 5.9.1)
CPU Architecture: x86_64
Operating System: Debian GNU/Linux 9 (stretch)
Platform Plugin:  xcb
```

##### STEPS TO REPRODUCE

1. Create or open any local library in Library Editor;
2. Go to menu "File".

##### EXPECTED RESULTS

There should be NO menu entries "Save Element" and "Remove Element" in "File" menu while there are NO active elements.

Those menu entries should be visible only if some element would be opened for editing.

![pic.1](http://i.imgur.com/Cg3XTRp.png)

##### ACTUAL RESULTS

"Save Element" and "Remove Element" are shown in "File" menu while there are NO active elements.

![pic.2](http://i.imgur.com/aXeAdD9.png)

**Comment by ubruhin** [comment]
Regarding "Remove Element": This is already reported in #200 and will be fixed with #380.

And regarding "Save Element", this is also needed if no element is open because then it saves the library metadata (i.e. if you change the metadata of the library itself you also need to save it with this menu item). Maybe this could be made more intuitive by renaming "element" with the actual element name, then the menu item is named for example "Save 'SOT-23'" or "Save 'LibrePCB Base'".
