### ISSUE TITLE
Use a default component style on schematic & component selector

### ISSUE THREAD

**Issue by hooperbloob** [LibrePCB/LibrePCB#396]
I love LibrePCB's capability to present alternate renderings for components, i.e. 
American vs European component symbols.  Can users select their preferred 
style as a preference option to show on the component selector and the schematic
itself?  Maybe have the option to choose the preferred style when the library is
first loaded.

**Comment by dbrgn** [comment]
Hi, thanks for the suggestion!

I think this is something that's already planned. @ubruhin did you intend to use the "norm" field for this? In that case we would probably need to standardize the values somehow.

Are there other symbol variant choices besides IEEE (US) vs IEC (EU)?

Maybe the design of such a feature should be discussed at https://librepcb.discourse.group/ since there are still quite a few open questions.

**Comment by hooperbloob** [comment]
Glad to hear.   Not being able to render schematics with your preferred symbols is like dealing with the loss of favourite words from your vocabulary.

**Comment by ubruhin** [comment]
Yes, this is intended, and parts of it are already implemented. In the workspace settings you can choose your preferred norm(s):

![grafik](https://user-images.githubusercontent.com/5374821/50311964-319e0580-04a7-11e9-9212-5343ea1b682d.png)

But as far as I remember, it's not yet used at all :grin:
