### ISSUE TITLE
Board editor: Add device by double-click or drag-and-drop

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#527]
##### SUMMARY
In pcb, to place a device we have to click on it and go to the bottom of the window to click "add" button

##### SOLUTION
Double-click on the device or draging the device from the list to the pcb field starts the adding process !
It is simple to do (at least for double click) and user friendly !

**Comment by ubruhin** [comment]
The only question is which device and footprint to choose then, since the user wouldn't be able to choose. Maybe allow the double-click only if the device is already pre-selected in the schematic (see also #529) to avoid adding a random (probably wrong) device?

The footprint is less critical, we should then just use the default footprint of the selected package.

**Comment by doom-fr** [comment]
Maybe just use what is written in the device and footprint fields. If the user needs another one, he will change before.
And also allow to drag and drop the footprint representation (as it is a very big field, it will be the easiest and fastest method with the mouse).

I also noticed that if I change the device (shouldn't it be device type ?) and/or footprint of a component, click on another one and go back to the first, the changes are lost.

**Comment by ubruhin** [comment]
With #892, devices can now be added with double-click so I think we can close this :tada:
