### ISSUE TITLE
Library Editor: Wrong top pin text rotation

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#534]
##### SUMMARY & SOLUTION
Set top pins text same orientation as bottom ones, like classic texts
(I know that it is preferable to make functional symbol, but I will do both)

![image](https://user-images.githubusercontent.com/7809481/66323808-a6520b80-e924-11e9-9cf2-0d3ef3737c4f.png)

**Comment by dbrgn** [comment]
(Unrelated comment: In case you want to contribute parts to the official libraries, we prefer pin placement only on the sides: https://docs.librepcb.org/#libraryconventions-symbols-pinplacement)

**Comment by doom-fr** [comment]
No problem, as explained, I will do both placement type symbol : functional and physical.

**Comment by dbrgn** [comment]
Ah, I overlooked that :slightly_smiling_face:

**Comment by ubruhin** [comment]
This seems to be a bug in the symbol editor - as soon as the symbol is added to a schematic, rotation is pin texts is correct.

**Comment by mexchip** [comment]
I was checking this one, and found that in libs/librepcb/library/sym/symbolpingraphicsitem.cpp the pin is not directly drawn but as different components elsewhere (I didn't found where), while in libs/librepcb/library/sym/symbolpinpreviewgraphicsitem.cpp the _updateCacheAndRepaint_ and _ _paint_ method take into account the orientation, I thought implementing the _paint_ method in the former would fix it but was not able to get it working:

- Trying to edit mTextGraphicsItem rotation and position in symbolpingraphicsitem.cpp is difficult since not able to access several properties (sizes, layers, etc.) directly because not part of the class.
- If trying to implement the _paint_ method in symbolpingraphicsitem.cpp, the drawing duplicates, still.
- If overriding the QGraphicsItem(parent) initializer in symbolpingraphicsitem.cpp with QGraphicsItem() trying to avoid painting twice, the pin is not drawn at all.

I was about to ask for some guidance, then I noticed this other issue: #181, maybe this issue could be deprecated in favor of #181, or still be worked by itself?

**Comment by ubruhin** [comment]
I suspect the issue is in `PrimitiveTextGraphicsItem`, which looks a bit ugly anyway :wink::

https://github.com/LibrePCB/LibrePCB/blob/2e747216114042648c9677d7c18301b793b80918/libs/librepcb/common/graphics/primitivetextgraphicsitem.cpp#L134-L145

**Comment by mexchip** [comment]
I've made some changes and it seems to work better now. I've finished rebasing so that you can have a look at it.
