### ISSUE TITLE
Package Editor: Add a Pad Stack Editor

### ISSUE THREAD

**Issue by EdizonTN** [LibrePCB/LibrePCB#594]
Again, based on discussion ( https://librepcb.discourse.group/t/gerber-files-solved/159/4 ),
I call for new feature: **Pad Stack Editor**

Pad stack editor allow define diferrent pad shape for each layer (THD pad of course).

example:
![padstack](https://user-images.githubusercontent.com/48570749/69496663-cb9ad900-0ed4-11ea-96d1-c2826724c11d.gif)

**Comment by ubruhin** [comment]
I implemented a similar feature in #1097, see details there. Basically it allows to shrink the pad size on solder side and inner layers to a minimal annular ring to heavily reduce the needed space. Since that feature will be part of the next release, I'm not sure if we need to make it even more complex, e.g. like the screenshot in the post above. So my suggestion is to close this issue for now - but of course I'm open for inputs if the new feature is not sufficient.

Please don't hesitate to reopen this issue if you think this is still needed.
