### ISSUE TITLE
Board Editor: Prevent error "Nothing to connect."

### ISSUE THREAD

**Issue by mrm2m** [LibrePCB/LibrePCB#631]
##### SUMMARY

If you miss the trace which you want to draw to by just a few mm you will see the message "Nothing to connect".

##### SOLUTION

Find out if there are trace nodes in reasonable distance (like 1cm) around the click position and select the one which is nearest if there is no direct match.

**Comment by miniwark** [comment]
I have a similar case of "nothing to connect error", with a handmade component, even if the wire was apparently at the same place than the connection pin. I suspect than the pin was 1 or 2 pixels away from the grid, and the trace try to "snap to grid" instead of "snap to pin".

Also., I have solved the issue by recreating the component from start in the library. Wile doing this, there seem to have a steep, in the Wizard that not editable in the library: In the "Pin-Signal-Map" i have clearly indicated "pin" int the Designator in Schematics" column, and suspect then this steep is important to connect correctly in the schematics (but i do not have find a way to edit this in the library).

**Comment by 5n8ke** [comment]
Simply choosing the closest NetPoint would not suffice in my opinion. Pads, Vias, and even the closest distance to the traces must be taken into consideration.
And should the currently selected layer for routing be considered as well?
