### ISSUE TITLE
Allow changing properties of unconnected footprint pad

### ISSUE THREAD

**Issue by dbrgn** [LibrePCB/LibrePCB#641]
##### VERSION / OS / ENVIRONMENT

```
LibrePCB Version: 0.1.3
Git Revision:     56bc60d347ff67df0fe1d57807d03f0606de557f
Build Date:       2019-12-04T19:59:17
Qt Version:       5.13.2 (built against 5.13.2)
CPU Architecture: x86_64
Operating System: Arch Linux
Platform Plugin:  xcb
```

##### SUMMARY

An unconnected pad can be placed in a package, but after placing it the properties (e.g. size) cannot be changed anymore:

![2019-12-28-144259_461x298_scrot](https://user-images.githubusercontent.com/105168/71544490-5cefe600-2980-11ea-9c83-569e8c39a5a8.png)

##### STEPS TO REPRODUCE

1. Add an unconnected pad to a package
2. Double-click it to open the dialog
3. Click on "Apply"

##### ADDITIONAL INFORMATION

This will probably get fixed by #445, but maybe there's a simple quickfix for this that doesn't require a file format update.

**Comment by ubruhin** [comment]
The thing is, such a pad is actually not unconnected (the underlying data structure does not allow creating unconnected pads). The "(not connected)" in the UI is wrong because the dropdown only lists unused package pads. And we should not change this since otherwise it would be much easier to create footprints with multiple pads with the same UUID, i.e. invalid footprints.

Thus currently the *real* issue is that the "add pad" tool allows to add more pads, even if all package pads are already used.
