### ISSUE TITLE
Board Editor : Bug : Round shaped plane is half filled

### ISSUE THREAD

**Issue by doom-fr** [LibrePCB/LibrePCB#948]
##### VERSION / OS / ENVIRONMENT
```
LibrePCB Version: 0.1.6
Git Revision:     c4f3164
Build Date:       2021-11-02T19:29:07
Qt Version:       5.15.2 (built against 5.15.2)
CPU Architecture: x86_64
Operating System: Ubuntu 21.10
Platform Plugin:  xcb
TLS Library:      OpenSSL 1.1.1l  24 Aug 2021
```

##### SUMMARY
Round shaped plane is half filled

![image](https://user-images.githubusercontent.com/7809481/149591488-ba22b3c2-ec29-4954-be02-55480e7190e7.png)

##### STEPS TO REPRODUCE

![image](https://user-images.githubusercontent.com/7809481/149591535-c515e6d7-dce2-4cb8-8c1c-cdd846cc56f1.png)

##### EXPECTED RESULTS
full circle filled

##### ACTUAL RESULTS
half circle filled

##### ADDITIONAL INFORMATION

This works : 
![image](https://user-images.githubusercontent.com/7809481/149591820-219fc033-8df7-4f88-8358-8b3bbb606be5.png)
![image](https://user-images.githubusercontent.com/7809481/149591953-b574f016-d2d2-4b7b-bdb4-37f8788924df.png)

**Comment by ubruhin** [comment]
Hm generally the problem with your plane is that the last vertex is missing - a closed path requires at least 3 vertices, not 2. But of course a half-filled plane is not the behavior we expect, even when a vertex is missing. Either we should handle planes like polygons - which are not filled at all if they have less than 3 vertices - or we could automatically add an implicit last vertex to make it a closed path even if the last vertex is missing (because non-closed planes make no sense, in contrast to polygons). I'll try to decide and fix this for the next release.

Thanks for reporting!

**Comment by doom-fr** [comment]
I do not know exactly what should be done, but this is mandatory : 
if we see a full circle for the outline of the plane, it should fill the full circle.
